site_name: "KOH-GPJax"
site_description: "Documentation website for KOH-GPJax"
site_author: "James Briant"
copyright: "Copyright © 2025 James Briant"
repo_url: "https://github.com/jamesbriant/koh-gpjax/"
repo_name: "jamesbriant/koh-gpjax"
edit_uri: edit/main/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: "material"
  features:
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

# nav:
#   - Overview: index.md
#   - API reference: api/
#   - License: LICENSE.md

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic : true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
            - "https://docs.python.org/3/objects.inv"
          options:
            docstring_style: google
            show_submodules: false
          paths: [kohgpjax]
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/jamesbriant"


extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css